services:
  nginx:
    container_name: nginx
    image: nkl322/django-pet-nginx:latest
    ports:
      - "80:80"
    networks:
      - app_network
    depends_on:
      - backend

  backend:
    container_name: backend
    image: nkl322/django-pet-backend:latest
    command: sh -c "poetry run python manage.py migrate && \
      poetry run gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - prod.env
    networks:
      - app_network
    depends_on:
      - postgres

  celery_worker:
    container_name: celery_worker
    image: nkl322/django-pet-backend:latest
    command: poetry run celery -A core worker --loglevel=info
    env_file:
      - prod.env
    networks:
      - app_network
    depends_on:
      - redis

  celery_beat:
    container_name: celery_beat
    image: nkl322/django-pet-backend:latest
    command: poetry run celery -A core beat --loglevel=info
    env_file:
      - prod.env
    networks:
      - app_network
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app_network

  postgres:
    container_name: postgres
    image: postgres:alpine
    env_file:
      - prod.env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
