services:
  frontend:
    image: nkl322/django-pet-frontend:latest
    build:
      context: ./frontend
      target: dev
    ports:
      - "4200:4200"
    env_file:
      - dev.env
    volumes:
      - "./frontend/src:/home/nkl/frontend/src"

  backend:
    image: nkl322/django-pet-backend:latest
    build:
      context: ./backend
      target: dev
    ports:
      - "8000:8000"
    env_file:
      - dev.env
    volumes:
      - "./backend/core:/home/nkl/backend/core"
      - "./backend/api:/home/nkl/backend/api"
    depends_on:
      - db

  db:
    image: postgres:alpine
    volumes:
      - dev_db_data:/var/lib/postgresql/data
    env_file:
      - dev.env

volumes:
  dev_db_data:
