services:
    backend:
        image: nkl322/django-pet-backend:latest
        build:
            context: ./backend
            target: ${TARGET:-dev}
        ports:
            - "8000:8000"
        volumes:
            - "./backend/core:/home/nkl/backend/core"
            - "./backend/api:/home/nkl/backend/api"
        env_file:
            - .env.${TARGET:-dev}
        depends_on:
            - db

    frontend:
        image: nkl322/django-pet-frontend:latest
        build:
            context: ./frontend
            target: ${TARGET:-dev}
        ports:
            - "4200:4200"
        volumes:
            - "./frontend/src:/home/nkl/frontend/src"
        depends_on:
            - backend

    db:
        image: postgres:latest
        volumes:
            - db_data:/var/lib/postgresql/data
        env_file:
            - .env.${TARGET:-dev}

volumes:
    db_data:
