services:
  frontend:
    image: nkl322/django-pet-frontend:latest
    build:
      context: ./frontend
      target: dev
    ports:
      - "4200:4200"
    env_file:
      - dev.env
    environment:
      SENTRY_DSN: ${SENTRY_DSN_FRONTEND:-}
      COMMIT_SHA: ${COMMIT_SHA:-}
    volumes:
      - "./frontend/src:/home/nkl/frontend/src"
    networks:
      - app_network

  backend:
    image: nkl322/django-pet-backend:latest
    build:
      context: ./backend
      target: dev
    ports:
      - "8000:8000"
    env_file:
      - dev.env
    volumes:
      - "./backend/core:/home/nkl/backend/core"
      - "./backend/api:/home/nkl/backend/api"
    networks:
      - app_network
    depends_on:
      - db

  db:
    image: postgres:alpine
    volumes:
      - dev_db_data:/var/lib/postgresql/data
    env_file:
      - dev.env
    networks:
      - app_network

volumes:
  dev_db_data:

networks:
  app_network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: "1400"
