services:
  nginx:
    image: nkl322/django-pet-nginx:latest
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

  frontend:
    image: nkl322/django-pet-frontend:latest
    build:
      context: ./frontend
      target: prod
      args:
        SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN}
        SENTRY_ORG: ${SENTRY_ORG}
        SENTRY_DSN: ${SENTRY_DSN_FRONTEND}
        SENTRY_PROJECT: ${SENTRY_PROJECT_FRONTEND}
        BUILD_SOURCE_MAP: ${BUILD_SOURCE_MAP:-false}
        COMMIT_SHA: ${COMMIT_SHA:-}

  backend:
    image: nkl322/django-pet-backend:latest
    build:
      context: ./backend
      target: prod
      args:
        DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
    env_file:
      - prod.env
    depends_on:
      - db

  db:
    image: postgres:alpine
    env_file:
      - prod.env
    volumes:
      - prod_db_data:/var/lib/postgresql/data

volumes:
  prod_db_data:
