version: "3"

services:
    backend:
        build:
            context: ./Dockerfiles
            dockerfile: Dockerfile.backend
        ports:
            - "8000:8000"
        # depends_on:
        #     - db
    # db:
    #     image: postgres:latest
    #     environment:
    #         - POSTGRES_DB=value
    #         - POSTGRES_USER=value
    #         - POSTGRES_PASSWORD=value
    #     ports:
    #         - "5432:5432"